### PR TITLE
Delayed command feature

### PR DESCRIPTION
**Pull request by ReinWD**
I added a field called "delayed" for most of the powers so that we can use a int variable to describe how long we need to delay before a command takes place.

Usage: 
construct a power with a int param "delay"
or use
/rpgitem set <item.name> <power.name> <power.No> delay <ticks>
to apply a delayed command or power(default 0). 

most powers are supported.

test passed in 1.12.

*unsupported power     and its cause

PowerAttract            //high frequency
PowerConsume            //due to potential of multiple use
PowerConsumeHit         //due to potential of multiple use
PowerDeathCommand       //due to potential of multiple use
PowerDeflect            //isn't suitable
PowerLoreFilter         //no need
PowerNoImmutableTick    //no need
PowerParticleTick       //high frequency
PowerPotionTick         //high frequency
PowerRanged             //no need
PowerRangedOnly         //no need
PowerRescue             //Rescue needs quick action
PowerSelector           //no need
PowerTicker             //high frequency
PowerUnbreakable        //no need

### CODE REVIEW

**Comment by ReinWD** [comment]
test server available on reinwd.xyz

**Comment by Librazy** [comment]
Actually we can give these power that can be delayed a interface like `PowerDelayable`, and move the delay to where these power are triggered.

**Comment by ReinWD** [comment]
@Librazy I thought about that. But maybe it won't contain any methods, just a mark. Because I think it's no need to distinguish non-delayed task and delayed task (if it doesn't slow down performance). Delay 0 means that it will be executed immediately. Adding a method-contented Interface means the change of architecture. Maybe we can change the way method was called in the future .

**Comment by Librazy** [comment]
Actually `runTaskLater` with 0 delay means task will run in **next** tick, not immediately. That may cause some problems. And there are some duplicated code in each delayable power which can be unified.

**Comment by RecursiveG** [comment]
One issue for making powers delayable is that
game state can be different before and after the delay.
(e.g. Players can go offline, blocks may be modified, etc.)
@Librazy may want to check all such cases.

@ReinWD I suggest making one PR for each delayable power 
(or at least one commit for each power,) instead of one huge patch.
Thus the codes can be reviewed more easily.

BTW: Removing the duplicated code is not the focus now.
~I will trash all those garbages someday, hopefully.~

**Comment by ReinWD** [comment]
new version created.

**Pull request closed without merging**
